eazybankCommon:
  deployment:
    appName: &appName cards
    replicaCount: 1
    containerPort: 9000
    image:
      tag: s17
      repository: "92khsang/cards"

  service:
    appName: *appName
    port: 9000
    targetPort: 9000
    serviceType: "ClusterIP"

  enabledFeatures:
    - appname
    - profile
    - config
    - otel
    - kubernetesdiscovery