eazybankCommon:
  deployment:
    appName: &appName accounts
    replicaCount: 2
    containerPort: 8080
    image:
      tag: s17
      repository: "92khsang/accounts"

  service:
    appName: *appName
    port: 8080
    targetPort: 8080
    serviceType: "ClusterIP"

  enabledFeatures:
    - appname
    - profile
    - config
    - otel
    - kafka
    - kubernetesdiscovery