apiVersion: v1
kind: Service
metadata:
  name: {{ include "eazybank.serviceName" .Values.service }}
spec:
  selector:
    app: {{ .Values.service.name }}
  type: {{ .Values.service.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.ports.port }}
      targetPort: {{ .Values.service.ports.targetPort }}
      protocol: TCP