{{- if (include "eazybank.createService" .) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eazybank.serviceName" . }}
spec:
  selector:
    app: {{ include "eazybank.labelName" .Values.service }}
  type: {{ .Values.service.serviceType | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- end -}}