eazybankCommon:
  deployment:
    appName: &appName loans
    replicaCount: 1
    containerPort: 8090
    image:
      tag: s17
      repository: "92khsang/loans"

  service:
    appName: *appName
    port: 8090
    targetPort: 8090
    serviceType: "ClusterIP"

  enabledFeatures:
    - appname
    - profile
    - config
    - otel
    - kubernetesdiscovery
